# App
spring.application.name=schedulrx

# Hide stack traces from error responses
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never

# Hide server version header
server.server-header=

# Limit request body size
server.tomcat.max-http-form-post-size=10KB